### ISSUE TITLE
Documentation examples need improvement to use a stream of data

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/pypi.streamsx.database#21]
Including code examples in the documentation is definitely very useful.  To make it even more easy to use and ready for someone to modify, it should address the most common scenario which is how to use the package with a stream of data.

For example, the first sample:
```
sql_insert = 'INSERT INTO RUN_SAMPLE (A, B) VALUES ('hello', 'world')'
sql_drop = 'DROP TABLE RUN_SAMPLE'
s = topo.source([sql_create, sql_insert, sql_drop]).as_string()
res_sql = s.map(db.JDBCStatement(credentials))
res_sql.print()
```
uses hard coded data, which is not the most common scenario.

The second issue is, further down in the doc there are examples for inserting but it is missing the important step of showing that the stream of data needs to be converted to a structured stream.
For a beginner who is new to the Python API and the programming model, it was confusing.

I would recommend updating the examples to just show some generated data as the sample stream you want to insert, and show that it has to be converted to a sample schema so that the sample is complete and someone can copy and use it without missing a step.

Lastly, using 'A,B' for both the parameter name and tuple attribute name is confusing:

```
sample_schema = StreamSchema('tuple<rstring A, rstring B>')
...
stmt.sql = 'INSERT INTO RUN_SAMPLE (A, B) VALUES (?, ?)'
stmt.sql_params = 'A, B'
```

**Comment by markheger** [comment]
The documentation of the sample code should be updated in `_database.py`  and `__init__.py`.
