### ISSUE TITLE
map should return error tuples 

### ISSUE THREAD

**Issue by bienenstocks** [IBMStreams/pypi.streamsx.database#24]
JDBCRun returns an error port, but the python wrapper has no way to access this port.
Requesting an enhancement to implement a workaround for map to return error tuples only and not insert results.

**Comment by markheger** [comment]
- a new property should be provided to set the error output attribute
if set the output of JDBCStatement should contain the error attribute (tuple)

**Comment by markheger** [comment]
no demand anymore
